### ISSUE TITLE
請問這個是什麽錯誤

### ISSUE THREAD

**Issue by lofangmeng** [xiaohuiduan/cgan_anime_face#1]
![image](https://user-images.githubusercontent.com/75239990/135791274-7322bf31-6f17-477a-a92b-247d782f2bee.png)

**Comment by xiaohuiduan** [comment]
@lofangmeng  你是调用bulid_generator_model方法出错了，还是使用plot_model方法出错了？

**Comment by lofangmeng** [comment]
都會出錯，是不是我的tensorflow 版本使用到2.00+版本有關

**Comment by lofangmeng** [comment]
環境的設定只需要按照你寫的就好對吧

**Comment by xiaohuiduan** [comment]
@lofangmeng  tensorflow版本不一致很有可能会出错。你可以根据我的readme查看具体的tensorflow版本

**Comment by lofangmeng** [comment]
好的 謝謝 問題解決了
我跑了GUI muqian1出現了這個新的問題
![image](https://user-images.githubusercontent.com/75239990/135797630-29af2f15-b0e4-421e-98dd-82ca7d003f81.png)

**Comment by xiaohuiduan** [comment]
> 好的 謝謝 問題解決了 我跑了GUI muqian1出現了這個新的問題 ![image](https://user-images.githubusercontent.com/75239990/135797630-29af2f15-b0e4-421e-98dd-82ca7d003f81.png)

具体是在调用哪个函数的时候出错了？@lofangmeng

**Comment by lofangmeng** [comment]
![image](https://user-images.githubusercontent.com/75239990/136131689-bbfa2aee-13ee-4415-a985-87ec8ce3269a.png)
在載入模型的時候，我是直接運用現成的模型
![image](https://user-images.githubusercontent.com/75239990/136131758-65e1c88b-30f3-4261-8b94-36efcbf64ae5.png)

**Comment by lofangmeng** [comment]
![image](https://user-images.githubusercontent.com/75239990/136131984-ccfa2a1e-3d95-4479-9787-9d54127dd78c.png)
甚至稍微改了 變成另一個錯誤

**Comment by xiaohuiduan** [comment]
> ![image](https://user-images.githubusercontent.com/75239990/136131984-ccfa2a1e-3d95-4479-9787-9d54127dd78c.png) 甚至稍微改了 變成另一個錯誤

我刚刚去我电脑上面重新运行了一遍，是我的readme中关于lib版本写错了。正确的版本如下：
![image](https://user-images.githubusercontent.com/40485068/136189043-a2f5f8ff-9129-461f-b3d5-9ec5a3b5f4b0.png)

 使用如上图所示的keras和tensorflow的版本，在我的电脑上面运行没有问题。

**Comment by xiaohuiduan** [comment]
@lofangmeng 问题已经解决了吗？

**Comment by lofangmeng** [comment]
解決了 謝謝 我想請問如果我想使用tensorflow-gpu2以上的版本 請問作者相對於的keras 版本是什麽呢
因爲我想使用GPU訓練模型，tensorflowCPU訓練模型怕電腦壞掉

**Comment by xiaohuiduan** [comment]
你可以参考一下这个https://blog.csdn.net/Snowy_susu/article/details/103297021

**Comment by lofangmeng** [comment]
好那裏頭的IMPORT格式應該會有差吧‘

**Comment by xiaohuiduan** [comment]
> 好那裏頭的IMPORT格式應該會有差吧‘

import 应该不会变动（我也不确定），但是调用的某一些函数可能会出错（可能某些函数的传参发生了改变）
